# (generated with --quick)

from typing import List, Mapping, Union

argparse: module
codecs: module
logging: module
os: module
urllib: module

def _load_from_url(url: str, chinese_only = ...) -> Mapping[str, Mapping[str, Union[str, List[dict]]]]: ...
def _load_locally(fname: str, chinese_only = ...) -> Mapping[str, Mapping[str, Union[str, List[dict]]]]: ...
def _read_dict(dict_file: codecs.StreamReaderWriter, chinese_only = ...) -> Mapping[str, Mapping[str, Union[str, List[dict]]]]: ...
def greedy(wdict: Mapping[str, Mapping[str, str]], chunk: str) -> List[str]: ...
def lookup(wdict: Mapping[str, Mapping[str, Union[str, List[dict]]]], keyword: str) -> Mapping[str, Union[str, List[dict]]]: ...
def main() -> None: ...
def open_dictionary(fname: str, chinese_only = ...) -> Mapping[str, Mapping[str, Union[str, List[dict]]]]: ...
